### ISSUE TITLE
Build was sucessful but can't find launch file

### ISSUE THREAD

**Issue by ghost** [cab404/fiio-m3-editor#1]
Hello, 

I'm using 

Ubuntu 16.04 LTS

``` Bash
java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
```

I was able to git clone and build the program (after installing openjdk-8-jdk) however I didn't use the sudo privileges. Did i need to?

Now when I look for the editor i find nothing, I've tried fiio-playlist-editor, m3-playlist-editor and I cant find anything. 

Any suggestions?

Thanks for the help.

**Comment by cab404** [comment]
what command do you use to build project?

**Comment by ghost** [comment]
The ones in the readme file on git 

`./gradlew shadowJar`

**Comment by cab404** [comment]
ghh, email reply doesn't work
isn't there any jars in build/libs?

**Comment by cab404** [comment]
don't you have a jar in build/libs?

**Comment by ghost** [comment]
Yes there is a file `fiio-m3-editor-all.jar` in the /builds/libs directory.

**Comment by Joeslavins** [comment]
I'm a bit of a noob with Java

1. Assuming it is the file do I double click the jar to open it? or do I use come bash commands to make it work on Linux?

Also, would I need to install this file inside the M3 to make it work? or do I make the playlist in my system and just export it to M3?

**Comment by ghost** [comment]
Sorry I am a total noob at this, but I was able to launch through the terminal with the following commands (I explain them in a detail for others who might be just as nooby)

`cd ~/Git/fiio-me-editor/build/libs` - this is where i git cloned and built the program
`java -jar fiio-m3-editor-all.jar` - this is how i launched the program. 

It's working!!

Thank you soo much for this. This saves lives.

Couple of Observations
1. If a playlist is empty then the database of songs won't load and you can't add anything. 
2. Atm there seems to be no way to add playlists, is there a workaround?

**Comment by cab404** [comment]
1. i can't edit empty playlists because they are basically nonexistent, and why it's a problem is explained in 2
2. yup, and i can't fix it. there's an id created with each playlist, and it's stored in players internal memory. i just can't access it :(

basic workaround - add one song into each playlist and then edit it (and yup, you can't have more than 3 playlists (including favourites - it is a playlist too))

I am glad it helped someone :з
